stages:
  - build
  - prepare
  - release

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'


include:
  - local: .source/build.yml
  - local: .gitlab/ci/auto-release.yml

